Delete client directory
No-Country/c9-32-t-javareact pull request #1
Opened 2023-02-03 22:23 UTC by FaustoSav

Aceptame borrar este directorio asi subo le mio

2023-02-03 23:13 UTC, Tono2007 reviewed
PR ya con el nuevo que tienes

2023-02-04 00:23 UTC, KuroMicho commented
@FaustoSav hace la PR hacia la rama Develop, es para no hacer más commits directamente a la rama main.

2023-02-04 00:35 UTC, KuroMicho requested changes
denied

2023-02-04 00:42 UTC, KuroMicho approved these changes

2023-02-04 00:43 UTC, merged